AllCops:
  DisabledByDefault: true
  NewCops: enable
  Exclude:
    - Gemfile
    - "vendor/**/*"
    - "db/**/*"
    - "tmp/**/*"
    - "bin/**/*"
    - "node_modules/**/*"
  SuggestExtensions: false

# allow not exist comment/documentation
Style/Documentation:
  Enabled: false

# allow japanese commnets
Style/AsciiComments:
  Enabled: false

# allow 120 letters in row
Layout/LineLength:
  Max: 120

# escape freeze error
Style/FrozenStringLiteralComment:
  Enabled: false

Bundler:
  Enabled: true

Gemspec:
  Enabled: true

Lint:
  Enabled: true

Security:
  Enabled: true
